2019-06-10 00:16:19,261 ERROR : Exception on /index [GET] [in f:\python\flask\microblog\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "F:\python\Flask\microblog\app\routes.py", line 26, in index
    form = PostForm()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "F:\python\Flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "F:\python\Flask\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "F:\python\Flask\microblog\app\templates\index.html", line 7, in block "content"
    {{ form.hidden_tag()}}
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-06-10 00:16:40,181 ERROR : Exception on /index [GET] [in f:\python\flask\microblog\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "F:\python\Flask\microblog\app\routes.py", line 26, in index
    form = PostForm()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "F:\python\Flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "F:\python\Flask\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "F:\python\Flask\microblog\app\templates\index.html", line 7, in block "content"
    {{ form.hidden_tag()}}
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-06-10 00:16:41,601 ERROR : Exception on /index [GET] [in f:\python\flask\microblog\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "F:\python\Flask\microblog\app\routes.py", line 26, in index
    form = PostForm()
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "f:\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "F:\python\Flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "F:\python\Flask\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "F:\python\Flask\microblog\app\templates\index.html", line 7, in block "content"
    {{ form.hidden_tag()}}
  File "f:\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
